name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/workflows/metrics.yml"]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: tinyzqh
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
